# Colors for Yael Rice

# Default colors
[colors.primary]
background = "#0c050d"
foreground = "#edcade"

# Cursor colors
[colors.cursor]
cursor = "#edcade"
text = "#161616"

# Normal colors
[colors.normal]
black = "#0c050d"
red = "#702548"
green = "#9d2f5f"
yellow = "#DB2772"
blue = "#BC4962"
magenta = "#DD993E"
cyan = "#E15994"
white = "#edcade"

# Bright colors
[colors.bright]
black = "#a58d9b"
red = "#702548"
green = "#9D2F5F"
yellow = "#DB2772"
blue = "#BC4962"
magenta = "#DD993E"
cyan = "#E15994"
white = "#edcade"
